### ISSUE TITLE
L&P import incomplete after clearing the file storages and triggering the import

### ISSUE THREAD

**Issue by Vinai** [lizards-and-pumpkins/dev-vm#16]
When I clear the file system storage and run `sample-project/build/buildLizardsAndPumpkinsSnippets.sh`, the import ins strangely incomplete.

Visiting listing pages gives PHP notices:
```
Notice: Undefined index: price_mpd000c_website:en_country:EN in /vagrant/sample-project/vendor/lizards-and-pumpkins/catalog/src/Http/ContentDelivery/ProductJsonService/ProductJsonService.php on line 124
```

Actually, I'm not sure if this is the right repo for this issue or the sample-project.

**Comment by Schrank** [comment]
Can reproduce, but it happens right after `vagrant up`

Uncaught LizardsAndPumpkins\Http\ContentDelivery\Exception\NonExistingSnippetException: Snippet not available (key "price_acj003_website:en_country:EN") in /vagrant/sample-project/vendor/lizards-and-pumpkins/catalog/src/Http/ContentDelivery/PageBuilder/PageBuilderSnippets.php:139

**Comment by Schrank** [comment]
It is reproduceable, at least for me, after deleting sample-project and running vagrant up

http://demo.lizardsandpumpkins.com.loc/en/lafayette-convertible-dress.html can't be accessed.

    PHP message: PHP Fatal error:  Uncaught LizardsAndPumpkins\Http\ContentDelivery\Exception\NonExistingSnippetException: Snippet not available (key "price_wsd013c_website:en_country:EN")

**Comment by tim-bezhashvyly** [comment]
@Schrank But this is a different exception.

**Comment by Schrank** [comment]
You are right.
