### ISSUE TITLE
destination path 'sample-project' already exists

### ISSUE THREAD

**Issue by Schrank** [lizards-and-pumpkins/dev-vm#18]
> ==> default: fatal: destination path 'sample-project' already exists and is not an empty directory.

Delete it on provisioning or check and don't download again?

**Comment by tim-bezhashvyly** [comment]
What if developer already done some work with it and then executed provisioning? I'd say it's pretty hard to make provisioning idempotent. So not an issue.

**Comment by Schrank** [comment]
What about checking for sample project, if it exists, we don't clone and add a warning after provisining?

**Comment by tim-bezhashvyly** [comment]
This might work. And I don't even think we need a warning.

**Comment by Vinai** [comment]
How about we just do a `git pull origin master` if it already exists?

**Comment by tim-bezhashvyly** [comment]
I'm fine with it.

**Comment by Vinai** [comment]
Added the code to do a `git pull` only if it already exists.
