### ISSUE TITLE
Add explanation about consumerSupervisor to Readme

### ISSUE THREAD

**Issue by Schrank** [lizards-and-pumpkins/dev-vm#20]

**Comment by Vinai** [comment]
What would you like to know about it? How it works, how it is started by the init scripts, how to stop them etc?

**Comment by Schrank** [comment]
More how to use it.

How it works is sugar :)

**Comment by tim-bezhashvyly** [comment]
How about moving everything from readme to https://github.com/lizards-and-pumpkins/catalog/wiki/Demo-VM ? Or visa versa?

**Comment by Vinai** [comment]
I like having it in the readme. That would be the first place I would look. The wiki is more for long term reference. We can add it additionally to the wiki if you want.

@Schrank How to use the commandSupervisor is here: https://github.com/lizards-and-pumpkins/dev-vm#starting--stopping-services
