### ISSUE TITLE
php error after installation on windows

### ISSUE THREAD

**Issue by eisbehr-** [lizards-and-pumpkins/dev-vm#60]
I've got some problems installing the vm on my windows machine. The installation with `vagrant` runs and completes with no noticeable error. When browsing to `http://demo.lizardsandpumpkins.com.loc` afterwards, only two php errors were shown:

> Warning: require(/vagrant/sample-project/pub/../src/magento/lib/LizardsAndPumpkins/MagentoConnector/autoload.php): failed to open stream: No such file or directory in /vagrant/sample-project/pub/index-magento.php on line 42

> Fatal error: require(): Failed opening required '/vagrant/sample-project/pub/../src/magento/lib/LizardsAndPumpkins/MagentoConnector/autoload.php' (include_path='.:/usr/share/php') in /vagrant/sample-project/pub/index-magento.php on line 42

Is there something I did wrong or did I missed something to do?

**Comment by Schrank** [comment]
Unfortunately this is a problem with the connector being a wrong version.

Can you please checkout the connector in master in 

```
cd  <PATH>dev-vm/sample-project/src/magento/.modman/magento-connector
git checkout master
git pull
modman repair
```

**Comment by tim-bezhashvyly** [comment]
@Schrank should I update connector version in a sample project?

**Comment by eisbehr-** [comment]
Thank you for your quick answer. The problem with your workaround for me is, that I don't have and use `modman`. Is there a way without using modman, or do I have to install that tool too, to get the vm working?

**Comment by Schrank** [comment]
@eisbehr- modman is installed in VM :)

**Comment by eisbehr-** [comment]
Sorry, because of your used path I was thinking the commands should be executed outside of the VM. Running the commands inside was no problem and it seems to work now. Thank you!

**Comment by Schrank** [comment]
Thanks! Doesn't matter - but I should be clearer. We'll leave this open until the problem is fixed

**Comment by Vinai** [comment]
Thanks for your report, we just published a new version that takes care the problem won't happen again!
